name: Deploy Leaderboards

on:
  push:
    branches:
      - master
    paths:
      - 'BOTGC.Leaderboards/**'
      - '.github/workflows/deploy-leaderboards.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish Leaderboards
      run: |
        dotnet publish BOTGC.Leaderboards/BOTGC.Leaderboards.csproj \
          -c Release \
          -r linux-x64 \
          --self-contained true \
          -o published

    - name: Zip Leaderboards
      run: zip -r leaderboards.zip . -x '*.git*'
      working-directory: published

    - name: Install Azure CLI
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Azure Login
      run: |
        az login --service-principal \
          -u ${{ secrets.AZURE_CLIENT_ID }} \
          -p ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Get Leaderboards App Name
      run: echo "LEADERBOARDS_APP_NAME=$(terraform -chdir=BOTGC.Infrastructure output -raw leaderboards_app_name)" >> $GITHUB_ENV

    - name: Deploy Leaderboards
      run: |
        az webapp deploy --resource-group rg-botgcapps-prd \
          --name $LEADERBOARDS_APP_NAME \
          --src-path published/leaderboards.zip \
          --type zip
