name: Apply Terraform Infrastructure

on:
  push:
    branches:
      - master
    paths:
      - 'BOTGC.Infrastructure/**'
      - 'terraform/**'
      - '.github/workflows/infrastructure.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    outputs:
      api_app_name: ${{ steps.get_api_app_name.outputs.api_app_name }}
      leaderboards_app_name: ${{ steps.get_leaderboards_app_name.outputs.leaderboards_app_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init
      working-directory: BOTGC.Infrastructure
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: BOTGC.Infrastructure
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_project_name: "botgcapps"
        TF_VAR_environment: "prd"
        TF_VAR_member_id: ${{ secrets.MEMBER_ID }}
        TF_VAR_member_pin: ${{ secrets.MEMBER_PIN }}
        TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}
        TF_VAR_azure_face_api_key: ${{ secrets.AZURE_FACE_API_KEY }}
        TF_VAR_x_api_key: ${{ secrets.X_API_KEY }}
        TF_VAR_github_token: ${{ secrets.PAT_GITHUB }}

    - name: Get Api App Name
      id: get_api_app_name
      run: echo "api_app_name=$(terraform output -raw api_app_name)" >> "$GITHUB_OUTPUT"
      working-directory: BOTGC.Infrastructure

    - name: Get Leaderboards App Name
      id: get_leaderboards_app_name
      run: echo "leaderboards_app_name=$(terraform output -raw leaderboards_app_name)" >> "$GITHUB_OUTPUT"
      working-directory: BOTGC.Infrastructure